### ISSUE TITLE
Function subscribe - Uncaught (in promise) Error: "collection" is required(…)

### ISSUE THREAD

**Issue by daniel1943** [flipace/horizon-react#11]
I am trying to copy example in code comments:

```
   * const mapDataToProps = (props) => ({
   *   name: 'keywords', //my collection name right?
   *   query: { owner: props.currentUser}
   * });
```

And I get 2x:  Uncaught (in promise) Error: "collection" is required(…)

This works great(using object instead of function)
       `mainTableDataStream: (hz, props) => hz('keywords').findAll({ owner: props.currentUser })`

With function, I tried every possible combination but can't seem to make it work.

**Comment by daniel1943** [comment]
Another problem is when I update row like:

r.db("lovli").table("keywords_39c8a6fb745d").get(ID).update({"someField":55})

The above mapDataToProps object keeps OLD(unupdated) version of object  in the array while giving new one id of -1.

**Comment by angelbeltran** [comment]
I believe the "mapDataToProps" is suppose to be an object with the subscription/query mapping keyed at the desired prop name. 

`const mapDataToProps = {
  todos: (hz) => hz('todos')
};`

You've just provided a function that maps to an object.

**Comment by BBB** [comment]
@daniel1943 The correct return object shape is this:

``` JS
{
   mapDataToProps: (props) => ({
     mainTableDataStream: {
       collection: 'keywords',
       query: { owner: props.currentUser }
     }
   })
 }
```

The `query` is optional.
