### ISSUE TITLE
Connector unmounts itself when providing horizon as a prop

### ISSUE THREAD

**Issue by chrbala** [flipace/horizon-react#13]
I get the `Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the _class component.` error when providing Horizon as a prop directly.

``` javascript
import Horizon from '@Horizon/client'
import { Connector } from 'horizon-react'
import store from 'store'

export default class App extends Component {
    constructor() {
        super()
        this.horizon = Horizon()
        this.state = { ready: false }
    }

    componentWillMount() {
        var { horizon } = this
        var ready = this.ready = horizon.onReady(() => this.setState({ready: true}))
        horizon.connect()
    }

    componentWillUnmount() {
        this.ready.unsubscribe()
    }

    render() {
        var { ready } = this.state
        var { horizon } = this

        return !ready 
            ? <div>loading</div>
            : <Connector store={store} horizon={horizon}><div /></Connector>
    }
}
```

As an aside, this error would have been easier to catch if the component were named. Can you also name the Connector component so it's easier to debug?

**Comment by BBB** [comment]
Related to #17. Closing in favour of that. Would you mind testing #19 to see if it fixes your issue?

**Comment by chrbala** [comment]
I can't install the patch from the repo directly because there are no built files (and src is in .npmignore). When I tried to jerry-rig an installation from a clone of your repo, I was still having the issue.

You can try out my test yourself with https://github.com/chrbala/horizon-react-webpack-hmr-boilerplate/tree/horizon-react-test

**Comment by BBB** [comment]
@chrbala Thanks for that. I've updated the PR with a fix. It was todo with `setState` being called before the `Connector` component was mounted, rather than after it was unmounted, as I previously thought
