### ISSUE TITLE
Unsubscribe with horizon-react?

### ISSUE THREAD

**Issue by loujiayu** [flipace/horizon-react#17]
I got this error: `Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the _class component.`. 

Any idea about how to implement function unsubscribe with horizon-react?

**Comment by KeKs0r** [comment]
I am running into the same issue. I am also interested in some unsubscribing functionality on unmount. 

I checked the documentation and it seems that the horizon subscribe function returns a normal RxJS subscription. So it should be straight forward to add an unsubscribe on unmount.

**Comment by BBB** [comment]
This should be handled correctly by https://github.com/flipace/horizon-react/blob/91b06795e3d844287afdf72bc19d55d69f3a0843/src/components/subscribe.js#L60

Can you provide a test case to reproduce this issue?

**Comment by BBB** [comment]
Oh hang on. This is probably caused by https://github.com/flipace/horizon-react/blob/91b06795e3d844287afdf72bc19d55d69f3a0843/src/components/subscribe.js#L123 being called in `.unsubscribe()`

We could probably just remove this call from the method, as the state can't be used to do anything anyway.

**Comment by BBB** [comment]
@KeKs0r @loujiayu Can you `npm install git://github.com/flipace/horizon-react.git#fix-17` and confirm that #19 fixes the issue please?

**Comment by KeKs0r** [comment]
This seems to be doing the trick! Thanks @BBB 

although npm installing the branch directly, somehow didn't work for me. (files were missing)

**Comment by ktmn** [comment]
I'm using latest version and still get tons of these warnings.
