### ISSUE TITLE
Implement connection with redux.

### ISSUE THREAD

**Issue by flipace** [flipace/horizon-react#2]
In my experience a big issue with redux can be the connection between data otw and the store.
In order to make it as easy as possible to use horizon with redux and react which is a common combination it would be great to have this connection of horizon data and redux store built right into horizon-react.

It seems like [react-apollo](https://github.com/apollostack/react-apollo) does that and it could serve as inspiration for this feature.

Discussion about this connection can happen in here!

**Comment by flipace** [comment]
I added basic redux features in the "next" branch. A couple of things will change - e.g. the way you pass props to `subscribe` it's now subscribe({ mapDataToProps: {}, mapStateToProps: ()=>({}) }) and you can pass all of redux's `connect()` options and they will be passed to redux's `connect()`. So there's no need to use connect and subscribe.

The next step is to utilize the redux store for storing query data and use it as some kind of cache.

**Comment by flipace** [comment]
Base redux features are now in `master` on 0.2.0.

**Comment by flipace** [comment]
Data propagation to redux store is now in the "next" branch. Polishing  tbd.

**Comment by youfoundron** [comment]
@flipace, 

Love what you're doing here, let me know if there's anything you need help with.

Cheers,
Ron
