### ISSUE TITLE
Not ordering lexicographically

### ISSUE THREAD

**Issue by ktmn** [flipace/horizon-react#20]
Here's my query:

```
const mapDataToProps = {
  data: (hz, props) => hz('data').findAll({id: props.id}).order('timestamp'),
};
```

and here's the order I get the results in:

```
[
    {
        "id":"0f3d6310-8f44-4d4f-a991-9334d0087d48",
        "timestamp":"2016-08-18T12:33:41.429",
    },
    {
        "id":"85f97a31-3d08-4423-861a-0ef72e78c8b1",
        "timestamp":"2016-08-18T14:56:25.004",
    },
    {
        "id":"deb2664a-5c23-45e9-be29-6eabb848e297",
        "timestamp":"2016-08-18T09:54:58.776",
    },
    {
        "id":"eb27f4f7-6c57-4236-a511-1a0cf4891842",
        "timestamp":"2016-08-18T12:37:45.536",
    },
    {
        "id":"72a75788-9175-4cfd-96ab-d726bb7c889a",
        "timestamp":"2016-08-18T15:44:33.116",
    },
    {
        "id":"2037bdfc-8b0d-40a2-9612-59e4aa27b562",
        "timestamp":"2016-08-18T15:44:14.134",
    }
]
```

For the timestamp I'm using [js-joda](https://github.com/js-joda/js-joda) library which gives this ISO8601 string, which should work for lexicographical ordering.

If I use the data explorer in RethinkDB dashboard and use this query

`r.db('db').table('data').filter({id:'...'}).orderBy('timestamp')`

it orders them correctly.

Sorry if it's not caused by this library but any ideas what might be going wrong here?

**Comment by ktmn** [comment]
Also if I take the horizon object that's passed to the components props and use it to fetch the stuff then the results are also correctly ordered:

```
    this.props.horizon('data')
    .order('timestamp')
    .findAll({id: this.props.id})
    .fetch()
    .subscribe(data => console.log(data)); // logs correctly ordered array of results
```

**Comment by flipace** [comment]
hi @ktmn 

i successfully reproduced this issue and it seems like this is a bug within the horizon client:
https://github.com/rethinkdb/horizon/issues/780

i'm going to close this issue here, but feel free to ping me when there's any updates.
