### ISSUE TITLE
React.PropTypes warnings

### ISSUE THREAD

**Issue by ghost** [flipace/horizon-react#21]
Hello, 

I'm not sure if its an issue but I get a lot of those warnings and its anoying to develop in is there any new release that will fix this or can I disable those in some way?
`warning.js:44 Warning: You are manually calling a React.PropTypes validation function for the`store`prop on`_class`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.`
Thx

**Comment by BBB** [comment]
@Ezeky Feel free to submit a PR to fix this. You can find details here: https://fb.me/react-warning-dont-call-proptypes

**Comment by flipace** [comment]
@Ezeky i tried to debug this issue but I don't think this is caused by horizon-react. You probably use another library which triggers this warning. Can you please check the stack trace and find out where the custom proptype validation is triggered?
