### ISSUE TITLE
Update for horizon 2

### ISSUE THREAD

**Issue by flipace** [flipace/horizon-react#23]
Horizon 2 was released and it arrived with a bunch of great new features.

http://horizon.io/blog/horizon-2/

**Comment by arthurvi** [comment]
Is it an idea to define the horizon client as a peerDependency instead of including it in this project?

**Comment by flipace** [comment]
hi @arthurvi - absolutely yes, this will happen prior 1.0

**Comment by arthurvi** [comment]
Currently i'm not experiencing any issues when I just remove the horizon client from the node_modules/horizon-react/node_modules folder. Do you have a list of things that need to be fixed before 2.0 can be listed as dependency?

**Comment by flipace** [comment]
there shouldn't be any issues actually, i didn't have time yet to give it a spin though. 
if you encounter some hiccups though, please create new issues for them!

**Comment by arthurvi** [comment]
I worked with horizon-react and horizon 2.0 as peer dependency all day an didn't encounter any issues. Would you like me to open a PR that moves the horizon dependency in `package.json` to `peerDependencies`?

**Comment by KeKs0r** [comment]
I am also running this with horizon 2.0 Everything seems to be fine

**Comment by BBB** [comment]
@flipace @arthurvi My test branch relies on `v2` (https://github.com/flipace/horizon-react/pull/16) I could update it so that horizon is a peerDep and merge that branch in. 

@flipace do we need to make any changes to support the new queries that are available in `v2`?

**Comment by flipace** [comment]
@BBB i think that everything should work just fine. the only thing which could be added would be some form of support for the new aggregate queries.

i guess you can give it a spin and merge! 👍
