### ISSUE TITLE
Empty Result or not loaded yet

### ISSUE THREAD

**Issue by KeKs0r** [flipace/horizon-react#26]
Hi,

I am wondering how to distinguish if my Query has an empty Result (Array with 0 entries) or if it is not resolved yet. I want to use the feature to show a Loading Spinner, but don't want to show it when its loaded but just empty.

Any Ideas?

**Comment by BBB** [comment]
@KeKs0r the `<Connector />` accepts a `loadingComponent` prop. That should do what you're after.

**Comment by arthurvi** [comment]
Is there any way to do this for react native? Can the connector inject a isLoading boolean in the props?
