### ISSUE TITLE
What is `store`?

### ISSUE THREAD

**Issue by tjmehta** [flipace/horizon-react#28]
This may be a silly question, but I don't see `store` explained anywhere in the README.

(I am unfamiliar w/ Redux; I have only used Relay in the past)

**Comment by flipace** [comment]
Hi @tjmehta there are no silly questions :)

`store` is redux specific and is the place where data "would" be stored if horizon-react would use it.

In it's current version, passing the store prop to the connector is just kind of a shortcut for react-redux users.

I'm removing this dependency however in the next update.

**Comment by tjmehta** [comment]
Cool, I ended up figuring it out by looking at the bootstrap project. I left this issue open, as it points out a doc gap. Thanks for the reply :)

**Comment by tjmehta** [comment]
I like the idea of removing redux as a dep; in-theory tying horizon react to less does will allow for more developer flexibility. 

Although, I only _just_ started using the react horizon today for a very small website.

**Comment by flipace** [comment]
I removed the dependency in horizon-react@0.5.0

Let me know if something does not work for you!
Until then I'll close this.

**Comment by tjmehta** [comment]
Cool I will try this out soon. Do I just remove the store prop? (FYI docs still show store usage)

**Comment by flipace** [comment]
Yes! It'll mock the prop in the background then.

Thx for the doc info. Will update when i have time.

Am 04.10.2016 10:35 Nachm. schrieb "Tejesh Mehta" <notifications@github.com
