### ISSUE TITLE
Create barebones example app

### ISSUE THREAD

**Issue by flipace** [flipace/horizon-react#3]
In order to make it as easy as possible for people who did never use react, webpack or similar stuff to try horizon-react, a minimum example app should be created which should demonstrate the minimum needed dependencies for using this.

While lovli.js is already stripped down to some basic things, it still uses some stuff which is not necessary if you just want to quickly try horizon-react.

**Comment by chrbala** [comment]
I made a boilerplate that should fit: https://github.com/chrbala/horizon-react-webpack-hmr-boilerplate

**Comment by flipace** [comment]
thanks @chrbala ! I'll add it to the readme!
