### ISSUE TITLE
Will it subscribe different hz queries based based on props each time after rerender

### ISSUE THREAD

**Issue by xinyuanyu** [flipace/horizon-react#4]
I'm new to horizon and rethinkdb. 

I built my component with the following way: 

``` javascript
const mapData = [
  {
    name: 'matchedData', 
    query: (hz, props)=>{
      // return different hz queries based on different value of props.
    }}
]

class MyComp extends Component{...}
export default subscribe(mapData)(MyComp);`
```

I passed different props to MyComp from the parent component, and MyComp got rerendered, 
Will MyComp subscribe a different hz query after re-rendering?

**Comment by flipace** [comment]
Hey @xinyuanyu!

There were some issues/inconsistencies in the previous version of horizon-react. I implemented a couple of new things (such as the possibility to use just `subscribe` to also connect to redux store) and also improved they query handling.

**As for your question** yes, when you update to 0.2.0, the queries will be correctly created for the new props.

P.S.: You can now also just write this:

``` Javascript
const mapDataToProps = {
   matchedData(hz, props) => hz('todos').limit(props.limit)
}

// ... your component stuff

export default subscribe({
  mapDataToProps
})(MyComp);
```

**Comment by xinyuanyu** [comment]
trying v0.2.1 now, 

Got this from README:

``` javascript
const mapDataToProps = {
  todos(hz) => hz('todos')
};
```

Should a colon to be added after `todos`, or is this new syntax from ES7 or somewhere else? 

Anyway, I tried to added a colon, but got no todos in the props of the target component,
only props like dispatch and horizon could be found in the props.

**Comment by flipace** [comment]
Ah yes a colon should be added after todos.

You'll also have to write 

``` Javascript
subscribe({ mapDataToProps: yourMapDataObject })
```

now. This is due to the addition of redux functionality.

**Comment by xinyuanyu** [comment]
Thanks @flipace, I though any key of the parameter in subscribe was ok, so I set the parameter in the following way: 

``` javascript
subscribe({ myMapDataObject })
```

when I changed the key to mapDataToProps, everything works fine now.

**Comment by flipace** [comment]
Okay great! :)
