### ISSUE TITLE
Documentation: React Native link to issues page is broken

### ISSUE THREAD

**Issue by sunjay** [flipace/horizon-react#7]
https://github.com/flipace/horizon-react/blob/master/README.md#does-this-work-with-react-native

You have a double parenthesis on the line with the answer to the react native question which breaks the link.

You can see that it is broken here:

https://www.npmjs.com/package/horizon-react#does-this-work-with-react-native

**Comment by flipace** [comment]
Thank you!

Fixed in https://github.com/flipace/horizon-react/commit/0806ede99abd4153117d6191dc10f9cce5bfbd20
