### ISSUE TITLE
Mutations?

### ISSUE THREAD

**Issue by roman01la** [flipace/horizon-react#8]
Hi! Are you going to implement mutations support?

**Comment by flipace** [comment]
Hey @roman01la, I'm afraid I'm not sure what kind of mutations you mean. Could you be more specific?

**Comment by roman01la** [comment]
@flipace sorry, I mean for example storing data into collections. Right now I can see only subscriptions are supported. How one can put data onto Horizon collection?

**Comment by flipace** [comment]
Ahh, alright I thought you might mean stuff like relay/graphql mutations.

Currently, when you `subscribe()()` a component it will get `horizon` as property. So you can access it like `this.props.horizon` anywhere in your component and do stuff like `this.props.horizon('messages').store({ name: 'test' })`.

If you'd rather not subscribe() a component and just want to use the horizon client in the component there are two ways to accomplish this.

a) pass a custom horizon client instance to the connector, and use this client by importing it into your file (see https://github.com/flipace/lovli.js/blob/master/source/client/db.js)
b) use React context to access this.context.horizon

However, after some discussion yesterday I'm going to implement the possibility to do something like this:

``` Javascript
const mapDataToProps = (hz, props) => ({
    addNewTodo: (doc) => hz('todos').store(doc),
    todos: hz('todos')
})
```

This is also going to allow implementing dependent queries in one subscribe() call.
Does this help you?

**Comment by roman01la** [comment]
The last one looks nice. I was playing around with self made React connector https://github.com/roman01la/react-horizon until found yours, just wanted to know how you would implement mutations. Thanks! :)
