### ISSUE TITLE
Redux or React or both?

### ISSUE THREAD

**Issue by yankeeinlondon** [flipace/horizon-react#9]
I'm an EmberJS developer and I like the Redux framework pattern (although I am relatively new to it as like most Ember developers I have invested in EmberData). Anyway, being that Redux is completely framework agnostic and Ember has [a very well done "addon"](http://www.ember-redux.com/) to use Redux in Ember.  I'm hoping this might be the easiest bridge to connect Ember to Horizon.

There are too many moving parts for me to be completely certain if this is a good idea or a road of pain. I'm just raising this issue with the hope that someone with greater visibility might be able to help me to determine this.

I will try a very quick spike to see what happens but I suspect i'll bump into a wall in the dark room I currently reside in. 😉

**Comment by flipace** [comment]
hi @ksnyde, I'm not sure what you mean :)

horizon-react is meant to be used with React only - it uses Reacts lifecycle functions to handle stuff like caching, subscription updates etc.

If your idea was to use horizon-react for ember - that won't work. However, it'd be interesting to see how an ember version could look like!

**Comment by yankeeinlondon** [comment]
Well without digging in too much I had assumed that the primary mechanism of state transfer from server to client was via the Redux framework which is available to both React and Ember.

**Comment by michael-iglesias** [comment]
Hi @flipace,

I was wondering if you had any suggestions on how to move forward with Horizon & Redux?

**Comment by flipace** [comment]
Hi @michael-iglesias,

the "next" branch utilizes redux to cache subscriptions and data.

However, it's completely linked to react too, so it wont work standalone. I could look into creating a separate version though.

**Comment by yankeeinlondon** [comment]
Two things:
- if you do create a pure redux solution, I _am_ interested
- what other touchpoints does your addon add to react? I wouldn't have expected this and would love to learn from your experience

**Comment by flipace** [comment]
@ksnyde sorry for the delay..

horizon-react utilizes reacts lifecycle functions to do stuff like rerendering, checking if the queries need to be updated etc.
